language: python
dist: trusty
sudo: required
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y
install:
  - pip install --upgrade pip
  - python setup.py develop
script:
  - pytest --cov
  - generate_CMIP6_json_files ./yaml-templates/yaml-example.yml ./data/empty-test-files/ ./outputs
after_success:
- codecov
