language: python
dist: trusty
sudo: required
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y
  - pip install --upgrade pip
  - pip install -Ur dev-requirements.txt
  - python setup.py develop
script:
  - pytest
